name: Matrix Demo

on: push
jobs:
  build:
    strategy:
      matrix:
        node-version: [12, 14, 16]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get code
        uses: actions/checkout@v6
      - name: Install nodejs
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version  }}
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build
