name: First Workflow
# on event listener there are a lot of
on: workflow_dispatch
# Jobs
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello world!"
      - name: Print goodbye
        run: echo "Done - bye"
